import time
from EOS import speak
speak("10")
time.sleep(0.1)
speak("9")
time.sleep(0.1)
speak("8")
time.sleep(0.1)
speak("7")
time.sleep(0.1)
speak("6")
time.sleep(0.1)
speak("5")
time.sleep(0.1)
speak("4")
time.sleep(0.1)
speak("3")
time.sleep(0.1)
speak("2")
time.sleep(0.1)
speak("1")
time.sleep(0.1)
speak("0")
speak("WARNING LAUNCHING NOW...")